var pianoSheets = [
  "QPQPQNPOMHJMNJLNOJQPQPQNPOMHJMNJONMNOPQLRQPKQPOJPONNJQQQQPQPQNPOMHJMNJLNOJQPQPQNPOMHJMNJONMORQQPPRTSRQPONMMLMNOPPQRMOPNOPQSPNOPQSPNQQQQQP",
  "JJKLLKJIHHIJJIIJJKLLKJIHHIJIHHIIJHIJKJHIJKJIHIEJJKLLKJIHHIJIHH",
  "QPOPQSSSSTSTUVVVVVVUTSTTSSSQPOQRQPPQPPQPPPOOOOPOOTUVVVVVVUTSSSQPOVVVVWWWVWXXWVVVVVWWSSXWVVVVVWWWWVUVTTUTUVVVWVWXXWXV",
  "LOQSONQSSTUVTSQPOOOQPOOOPQPOMPQPLOQSONQSSTUVTSPOOOQPOOOPQPMNOPOQSQPOSNMNMNMLQSQPOSNMNOOOPQPLOQSONQSSTUVTSQPOOOQPOOOPQPMNOPO",
  "OOJLOOJLJJLOOMMKPPLMLKJIJLMLKJIJHLMOJLQPOLMJLMOJLQPOLMOLJLMLOOLJLMLOOLMOOLMPPLMQQLMQPO",
  "EHJJJJIJIHEHJHJLKJILKJJIHIJLKFFEGHIJIHLHJJJIJIHEHJJJLKJILKJJIHIJLKKFFEGIJIH",
  "FHIJLLJHIFHIJLLMIJJLMLMONMLMJHIJLHFHIJMLJMMLKJIJLFHIHIJLLMONMLJM",
  "LJIHIGFENMNLMKJLIJLIJKJIHLGIFHEFHECEFHIFHELOMLJLIIJGFEFHICHFEFHEJLGIFHECECEFGIFEFHILJIJIHFECHFHFECEFHEJLIJIHGFE",
  "QPQPQNPOMHJMNJLNOJQPQPQNPOMHJMNJONMNOPQLRQPKQPOJPONNJQQQQPQPQNPOMHJMNJLNOJQPQPQNPOMHJMNJONMORQQPPRTSRQPONMMLMNOPPQRMOPNOPQSPNOPQSPNQQQQQP",
  "HHHHGHIHIIIIHIJIHJMLJJMLJJJJJJMLKJIJKHIIIIIILKJIHLNMLKJNPONMLJJJJMLKJIJKHIIIIIILKJIHFGHIIJHHHHGHIHIIIIHIJIHJMLJJMLJOOOONNNNMNJIHGFMLJMMLJMJIHGHHLJMMLJMJIHGFLM",
  "LLQOPONOMKKNMLLLQONOPQRMMNONMNOLLMLMLRQPQOMNNMNMNOPRQPOSQSRQPRQONOPLJLJMLMLOLOLRPRPSSOPQRQPSQOPPQLMNOOPQRSQSQSSQSQRQPSRPRPRRQPRQSOLOQONOPQRMNMLMNPONO",
  "KKKKKKKKOPQRSTUTXWUTSSSSTUVWXYXTZYXWXVTZYXYZWVZXWVUVWXUSTVUVWXSSOTSRQPQRSRTOQRUTOTSSRRQPOO",
  "MLKJKJIKJFGFMLKNMKLMLKLKJJKLMNOPQQQPQRSTQRSRQPQQQPQRSTSTUOTMLKJKJIJKFGFMLKNMKLMLKLKJJKLMNOPQQQPQRSTQRSRQPQQQPQRSTSTUOTQQQQSQQQQSQQQQSQSQSQSQOOOUOPOONOPOPOPOPOQQPOMNLMNNMLMNOOPOONMLKLMMMKLMNNNNOQQRSSTVUTUVTMLKJKJIJKFGFMLKKMKLMLKLKJKLMNOPQQQPQRSTQRSRQPQQQPQRSTRQSRQPQQQPQRSTOPQRP",
  "JIHKJIJIHGHIJIHKJIJIHGHIJKLMMMMMNNNNMMMMNNNNMNMNMNMNMNNNNOOOONNNNOOOONONONONONMNOPONMNOPQRQPQMNOPONMNOPQRQPQQRSTSRQPONMLKJIHGFGHIHGFGHIJKJIJMNOPONMNOPQRQPQTSRQPONMLKJIHGEFFFFF",
  "QPQPQNPOMHJMNJLNOJQPQPQNPOMHJMNJONMNOPQLRQPKQPOJPONNJQQQQPQPQNPOMHJMNJLNOJQPQPQNPOMHJMNJONMORQQPPRTSRQPONMMLMNOPPQRMOPNOPQSPNOPQSPNQQQQQP",
  "EIIJIHHJKMOMMLLMGGMLHHJJIJIJIJIEIIJIHHJKMOMMLLMGGMLHHJJIJIJIHQOMLLIJKJIHQOMLKLMNPOOQOMLLIJKJIHQOMLKLMNOLNLOLNLOLNLOLNLOOOOEOPRQPSSSTQRPPPRQPOHNMLKJIOOPRQPSSSTQRPPPRQPOSPQO",
  "HHHHHHJIHGFEFGHIECBCCBCCBCBACBCCBCCBCFEECDFEECDFEECBGBFEEEFEDCCBCCBCBACBCCBCCBCFEECDJICIHGFEDCBAHHHGHHGHHGHKFHGHHGHHGHJEEEDDFFEEHGGFEDFFEDCEDDFFEEHGGEFHEEEFHGGHGGHGGGGJCBCCBCCBCBACBCCBCCBCFEECDFEEBCFEECBGBFEEEFEDCCBCCBCBACBCCBCCBCFEECDJICIHGFEDCBAHHH",
  "ELELLKJIHGFIFIEFGHIJELELLKJIHGGJGJGIJKGHHKKJIIHCCIHCCIHDDKKJIIHCCCDEFGHIJKMKKKJIIHCCIHCCIHDDKKJIIHCEEFGHJEHHOHOOONMLJILILHIJKLMHOHOOOMMLJILILJHIJJK",
  "IHDKKIHDKKIHDKBKAJJIHAJJIHAJJIHAJBJDKKIHMKKIHMKKIHMHOHPJJIHPJJIHPJJIHPHMHKMKKLMOOKLMOOKLMOOOPOMLKIIMLKIIMLKIIHIK",
  "EHHJJHEEEEIHGFEEHHJJHEHGFGHFEEGGHGFGHEHGGGKIGHHFFFHHEEEEEEIGHHFFFHHEEEEEIGHEHEHJHJHGHEEEEEEIHGFGFEEHEHJHJHGHEEEGFGHFDEEFEEGGGHGHHGHEHGGGKIGHHHHHFFFFHHHGHEEEEEEIJGHHHHHFFFFHHHGHEEEEEEIGIHCFFHHFCCCIHGFGCCCFFHHFCCCGFGHFCCCCGGHGHFCHGGIGHFCCCCDCBDCCFFEBCDCCDCBDCCFFGFC",
  "MOMJMJHJHFCFIGHGHGGHIGHFMOMJMJHJHFHGHHGHMHHGJKJJKJOJJIFHFEFIFEFKJIJHGFHGHGF",
  "QPQPQNPOMHJMNJLNOJQPQPQNPOMHJMNJONMNOPQLRQPKQPOJPONNJQQQQPQPQNPOMHJMNJLNOJQPQPQNPOMHJMNJONMORQQPPRTSRQPONMMLMNOPPQRMOPNOPQSPNOPQSPNQQQQQP",
];
var pianoAlph = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
var pianoAudio = {};
var soundtype = localStorage["soundtype"] || 0;

function loadPiano() {
  for (var i = 0; i < 26; i++) {
    var nowAudio = new Audio();
    nowAudio.src = "Sound/sound" + pianoAlph[i] + ".mp3";
    nowAudio.load();
    pianoAudio[pianoAlph[i]] = nowAudio;
    // console.log(pianoAudio);

  }}

  function sequencPlay(cr){
    
    // let cr = pianoAudio[ch]
    cr.currentTime = 0
    cr.play()
  }



  loadPiano();
  
let a = document.getElementById("a")

a.addEventListener("click", function(){
  console.log('a clicked');
  let cr = 0
  for (let ch of pianoSheets[1]){
   cr = pianoAudio[ch]
   setTimeout(sequencPlay(cr), 1000)
  
  }

  console.log(cr);
  // cr.play()

  
})





function randomPlay() {
  pianoPlay(pianoAlph[parseInt(Math.random() * 26)]);
}
function pianoPlay(a, e) {
  if (soundtype == 0) {
    var nowAudio = new Audio();
    nowAudio.src = "Sound/sound" + a + ".mp3";
    nowAudio.play();
  } else if (soundtype == 1) {
    var nowAudio = new Audio();
    if (e == 1) nowAudio.src = "error.mp3";
    else nowAudio.src = "touch.mp3";
    nowAudio.play();
  }
  if (soundtype != 2)
    nowAudio.onpause = function () {
      nowAudio = null;
    };
}
function cheerPlay() {
  if (soundtype != 2) {
    var nowAudio = new Audio();
    nowAudio.src = "cheer.mp3";
    nowAudio.play();
  }
}
// loadPiano();
// function changeSoundType(t) {
//   if (soundtype == 0) soundtype = 1;
//   else if (soundtype == 1) soundtype = 2;
//   else if (soundtype == 2) soundtype = 0;
//   localStorage["soundtype"] = soundtype;
//   randomPlay();
//   t.innerHTML = "Sound: " + ["Piano", "Default", "OFF"][soundtype];
// }
